apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: gcr.io/mapstitcher/api
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: mapstitcher-secrets
              key: postgres-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: mapstitcher-secrets
              key: redis-url
        - name: S3_ENDPOINT
          value: https://storage.googleapis.com
        - name: S3_BUCKET
          value: mapstitcher-storage
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mapstitcher-secrets
              key: storage-access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mapstitcher-secrets
              key: storage-secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: api
