apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: gcr.io/mapstitcher/worker
        env:
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: mapstitcher-secrets
              key: postgres-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: mapstitcher-secrets
              key: redis-url
        - name: S3_ENDPOINT
          value: https://storage.googleapis.com
        - name: S3_BUCKET
          value: mapstitcher-storage
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mapstitcher-secrets
              key: storage-access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mapstitcher-secrets
              key: storage-secret-key
