# .devcontainer/docker-compose.devcontainer.yml
version: '3.8'

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        # Add build-time arguments if needed
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
      - api-vscode-extensions:/root/.vscode-server/extensions
      - api-vscode-insider-extensions:/root/.vscode-server-insiders/extensions
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Add any development-specific environment variables
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  frontend:
    volumes:
      - ..:/workspace:cached
      - frontend-node-modules:/app/node_modules
      - frontend-vscode-extensions:/root/.vscode-server/extensions
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: sleep infinity

volumes:
  api-vscode-extensions:
  api-vscode-insider-extensions:
  frontend-node-modules:
  frontend-vscode-extensions:
